### ISSUE TITLE
Info log entries each time thie overview is activated

### ISSUE THREAD

**Issue by 73** [nathanielsimard/overview-navigation#16]
Hi,

thanks for this Extension. I use it daily. However, each time I activate the overview I get these log entries:
```
Nov 27 15:18:20 hostname gnome-shell[2202]: INFO - [Overview Navigation - CustomWorkspaceView] Animate to overview ...
Nov 27 15:18:20 hostname gnome-shell[2202]: INFO - [Overview Navigation - Search] Enabling search ...
Nov 27 15:18:21 hostname gnome-shell[2202]: INFO - [Overview Navigation - CustomWorkspaceView] On Destroy ...
Nov 27 15:18:21 hostname gnome-shell[2202]: INFO - [Overview Navigation - Search] Enabling search ...
Nov 27 15:18:21 hostname gnome-shell[2202]: INFO - [Overview Navigation - CustomWindowOverlay] Destroying ...
```
Maybe they can be suppressed?

**Comment by nathanielsimard** [comment]
Yes it can be suppress easily. The option `debug` could turn off all the logs, not just the one tagged `debug`, the option could also be called `logging` to be more general.

**Comment by nathanielsimard** [comment]
You can try the PR #17 by running the following command then restarting the shell (`Alt-f2 -> r` on X11 or log out / in on Wayland).

```sh
npm install
npm run local:install 
```

**Comment by 73** [comment]
That does fix it. Thanks.
