### ISSUE TITLE
Allow to style the hint label

### ISSUE THREAD

**Issue by 73** [nathanielsimard/overview-navigation#18]
It would be nice if the label style would be adjustable. 
Maybe by css or just the colors for:
- Font
- Background
- Border

**Comment by nathanielsimard** [comment]
It's possible to change the styling by changing the css `~/.local/share/gnome-shell/extensions/overview-navigation@nathanielsimard.github.com.stylesheet.css`, but maybe it would be easier with some settings.

**Comment by 73** [comment]
That would be overwritten on an update, would it not?

**Comment by nathanielsimard** [comment]
Hmm yeah, probably.

**Comment by nathanielsimard** [comment]
I implemented some basic style settings.

You can try the PR #19  by running the following command then restarting the shell (`Alt-f2 -> r` on X11 or log out / in on Wayland).

```sh
npm install
npm run local:install 
```

Let me know if there are some improvements to be made or if it's what you had in mind.

**Comment by 73** [comment]
Tested. Works perfectly. Beautiful!
