### ISSUE TITLE
White background and white font color make the text unreadable

### ISSUE THREAD

**Issue by lachhebo** [nathanielsimard/overview-navigation#21]
When i click on the space bar, the extension plot white boxes and i can't see the letter written inside them.

This is because the font color and the background color are both white by default. It can be easily fixed by update those default color.

I'm using fedora 31 with gnome 3.34.3

**Comment by nathanielsimard** [comment]
Thanks for reporting the issue, I don't know how to reset the settings for an extension, I guess the change in #23 fixes the problem, but I have no way to test it :disappointed: . If you did not change the defaults, could you test it ? If not, I'm still confident in the change, it's quite simple 😅.
