### ISSUE TITLE
Extension appear active but doesn't work on Gnome 3.38 (Debian testing)

### ISSUE THREAD

**Issue by rcdeoliveira** [nathanielsimard/overview-navigation#29]
I upgraded to gnome 3.38 on Debian Testing and the extension stopped working, appears active but nothing appears when space key is hit

**Comment by nathanielsimard** [comment]
It's probably a compatibility problem as usual with new GNOME versions. However, I'm not sure when I'll have the time to fix this.

If you want it quickly fixed, you can try to debug it yourself by enabling system logs. Otherwise you can just wait for me to fix it when I'll update to the new version.

**Comment by Mladia** [comment]
I am having the same problem, also on 3.38.
In the description it says that this is similar to winowNavigator, but I think windowNavigator is broken all the time. Do you think getting this functionality is still possible in the new version of Gnome?

**Comment by 73** [comment]
I know you said you will update the extension when you will find the time. I just wanted to pitch in and say your extension was appreciated and is missed now.

**Comment by nathanielsimard** [comment]
I updated the os on my laptop and tried to fix it quickly, but the labels still don't show up 😕. I'll have more time during the holidays to work on it.

**Comment by noreabu** [comment]
don't know if this helps, but this is from gnome-system-logs - applications:
```
18:16:27 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
18:16:27 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
18:16:27 gnome-shell: INFO - [Overview Navigation - Extension] Enabling extension ...
18:16:26 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
18:16:26 gnome-shell: INFO - [Overview Navigation - Extension] Disabling extension ...
17:56:13 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
17:56:13 gnome-shell: INFO - [Overview Navigation - Extension] Enabling extension ...
17:56:11 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
17:56:11 gnome-shell: INFO - [Overview Navigation - Extension] Disabling extension ...
17:27:50 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: main is undefined
17:27:50 gnome-shell: INFO - [Overview Navigation - Extension] Enabling extension ...
17:27:50 gnome-shell: ERROR - [Overview Navigation - Extension] TypeError: classToBeInjected is undefined
```
I am running Ubuntu 20.10, did the update from 20.04 today

**Comment by nathanielsimard** [comment]
I think I finally fixed it! You can try it by cloning the repo, and following the right instructions. It may help to know that it works on multiple instances of Gnome-3.38, not just my machine. I'll probably release it on Gnome Extension soon, but the process from sending the changes to the website and having it actually released is quite slow, so you may install it manually to have it earlier (as a Christmas Gift let's say).

So the instructions! You only need to have git and npm installed in order for it to work:

```bash
git clone https://github.com/nathanielsimard/overview-navigation
cd overview-navigation
git checkout gnome-3.38
npm install .
npm run build
npm run package
npm run local:install
```

After that you can only reset gnome shell and you're good to go (Alt+F2, r, enter on X11 | Log Out, Log In on Wayland)

**Comment by rcdeoliveira** [comment]
> I think I finally fixed it! You can try it by cloning the repo, and following the right instructions. It may help to know that it works on multiple instances of Gnome-3.38, not just my machine. I'll probably release it on Gnome Extension soon, but the process from sending the changes to the website and having it actually released is quite slow, so you may install it manually to have it earlier (as a Christmas Gift let's say).
> 
> So the instructions! You only need to have git and npm installed in order for it to work:
> 
> ```shell
> git clone https://github.com/nathanielsimard/overview-navigation
> cd overview-navigation
> git checkout gnome-3.38
> npm install .
> npm run build
> npm run package
> npm run local:install
> ```
> 
> After that you can only reset gnome shell and you're good to go (Alt+F2, r, enter on X11 | Log Out, Log In on Wayland)

Thanks @nathanielsimard , it's working on Debian testing. Good job!
