### ISSUE TITLE
Feature request : close window in overview

### ISSUE THREAD

**Issue by MonsieurLanza** [nathanielsimard/overview-navigation#5]
Hello, 
Great work, I love it. 
I would love to have the ability to close a window in the overview in a similar way.

I am not familiar with the gnome API, but I am JS developper myself. I may give it a try if it is not too time consuming.

**Comment by nathanielsimard** [comment]
I have been thinking about that feature for a moment now, I think the best way to implement it would be to have uppercase for closing window and lowercase for focusing window. Ex:

`Focus: ab Close: AB`

There is some refactoring to do before. 
- Testing [Window Selector](https://github.com/nathanielsimard/overview-navigation/blob/master/src/windowSelector.js) 
- Window Selector should close the overview

You don't really need Gnome Shell knowledge to implement it. If you want, you can give it a try starting with the refactoring.
