### ISSUE TITLE
Stopped working in Fedora 30

### ISSUE THREAD

**Issue by KappaDistributive** [nathanielsimard/overview-navigation#9]
After installing Fedora 30, this extension initially worked just fine but now has stopped working. It still shows the overlay but on pressing the particular key sequence, seemingly nothing happens.

How can I begin to troubleshoot this?

**Comment by KappaDistributive** [comment]
New insight: This seems to be related to external (or multiple monitors). I'm running a ThinkPad T490 with a docking station to which I've attached two monitors. While docked, the above issue occurs.

When using the laptop standalone, however, everything works just fine.

**Comment by KappaDistributive** [comment]
I think I'm getting to the core of this issue:

Enabling 'Workspaces span displays' in Gnome Tweak Tool fixes this issue.

**Comment by nathanielsimard** [comment]
I can't reproduce the issue on Ubuntu 19.04. You can add the logs so I can try to see what's the problem. 
`tail -f /var/log/syslog | grep "Overview Navigation"`

**Comment by FantacticMisterFox** [comment]
same problem here fedora 28. fedora has to my understanding no syslog at least i dont. I think the equivalent is /var/log/messages but i am not sudo on this machine, no reading rights. I check later on my laptop if i get the same problem. and get some meaning full errors.

**Comment by KappaDistributive** [comment]
As FantasticMisterFox has said, this log doesn't exist on Fedora. And since I've run into a couple of other issues with Gnome overview feature, I'd expect them to be filled with irrelevant information at the moment anyway.

Fortunately, ever since I've enabled 'workspaces span displays', I've not run into trouble with the navigator.

**Comment by nathanielsimard** [comment]
I tried to reproduce the problem on a live fedora session from a usb stick. The only bug that I encounter was that the labels don't hide on other displays when the option `Workspaces on primary display only` is selected as display handling option.

However it is still possible to focus the windows when the labels are visible on the primary screen.

**Comment by nathanielsimard** [comment]
@KappaDistributive @FantacticMisterFox Can you check if that [PR](https://github.com/nathanielsimard/overview-navigation/pull/11) fixes the problem ?

**Comment by KappaDistributive** [comment]
@nathanielsimard That version doesn't work at all for me. (It doesn't show an overlay, it doesn't block text input when pressing space in the overview, it doesn't select windows on keypress.)

Since I don't have much experience installing Gnome shell extensions manually, you might want to check whether I did something wrong:

I downloaded the PR, copied it to ~/.local/share/gnome-shell/extensions/ , deleted the old version, copied the UUID of the PR version and renamed the folder of the extension to said UUID (overview-navigation@nathanielsimard.github.com). Then I logged out, back in and enabled the extension via the Gnome Tweak Tool.

**Comment by nathanielsimard** [comment]
It won't work for sure. To install the extension manually juste copy the PR and run 
```
make install
```
It will do all the work. After you juste have to reload gnome-shell 
X11: `Alt-F2` followed by `r` and `Enter`
Wayland: log out and log in

Sorry for the lack of directions.

**Comment by KappaDistributive** [comment]
@nathanielsimard 

My bad. This PR does indeed fix the issue -- both with and without  'Workspaces span displays'.
